### ISSUE TITLE
 Xamarin.Forms.PinchZoomImage crash on ios

### ISSUE THREAD

**Issue by Sainty-dev** [TBertuzzi/Xamarin.Forms.PinchZoomImage#10]
the pinch tends to work fine on android , but on ios i get below crash 

note: version 1.1.0
SIGABRT: Position 68:34. Type pinch:PinchZoom not found in xmlns clr-namespace:Xamarin.Forms.PinchZoomImage;assembly=Xamarin.Forms.PinchZoomImage

**Comment by TBertuzzi** [comment]
Update to new version 1.2.0
