### ISSUE TITLE
Broken on iOS

### ISSUE THREAD

**Issue by mharrisonbit** [TBertuzzi/Xamarin.Forms.PinchZoomImage#3]
I am using this in a forms project and it works like a dream on droid but when I build iOS it dies. I get the error. 
Type pinch:PinchZoom not found in xmlns clr-namespace:Xamarin.Forms.PinchZoomImage;assembly=Xamarin.Forms.PinchZoomImage"

Here is the code that I am using.
```
<StackLayout VerticalOptions="CenterAndExpand" HorizontalOptions="Center">
   <pinch:PinchZoom>
       <pinch:PinchZoom.Content>
         <Image x:Name="DroidView"/>
       </pinch:PinchZoom.Content>
   </pinch:PinchZoom>
</StackLayout>
```

**Comment by zanesc** [comment]
This was working for me until recently. Did you ever resolve this issues?

**Comment by zanesc** [comment]
I have added an instantiation to the AppDelegate to workaround this issue:
```_ = new Xamarin.Forms.PinchZoomImage.PinchZoom();```

**Comment by mharrisonbit** [comment]
I haven't yet. I was moved to a different project so I haven't checked in a couple weeks. I'll check to see if that works in the morning

**Comment by TBertuzzi** [comment]
Update to version 1.1.0
