### ISSUE TITLE
Double Tap Zoomin/Zoomout

### ISSUE THREAD

**Issue by lumisoftusa** [TBertuzzi/Xamarin.Forms.PinchZoomImage#4]
HI,

Is there any way to add Double tap gesture for zoomin/zoomout.

**Comment by DECWebSites** [comment]
> Is there any way to add Double tap gesture for zoomin/zoomout.

that would be interesting and very useful

**Comment by janlengyel** [comment]
I just needed that function so if you are interested, I added a fork with that change. At the moment you can find it in "Pull requests" tab

**Comment by DECWebSites** [comment]
> I just needed that function so if you are interested, I added a fork with that change. At the moment you can find it in "Pull requests" tab

GOOD

**Comment by TBertuzzi** [comment]
Update to version 1.1.0
