### ISSUE TITLE
Error when pinch.

### ISSUE THREAD

**Issue by rpotalara** [TBertuzzi/Xamarin.Forms.PinchZoomImage#6]
Hi @TBertuzzi , I am installed you package, compile but when a try to pinch I receive error:
Erro:
Java.Lang.NoSuchMethodError
  Message=no method with name='<init>' signature='(Landroid/content/Context;Landroid/view/ScaleGestureDetector$OnScaleGestureListener;Landroid/os/Handler;)V' in class Landroid/view/ScaleGestureDetector;

XAML:
             xmlns:pinch="clr-namespace:Xamarin.Forms.PinchZoomImage;assembly=Xamarin.Forms.PinchZoomImage"
             x:Class="APP.View.ProductFotoPage">
    <ContentPage.Content>
        <StackLayout Padding="10,40,10,10">
            <pinch:PinchZoom>
                <Image x:Name="URLProductPhoto" Source="{Binding URLProductPhoto}" />
            </pinch:PinchZoom>

Can you explain me the problem and how to solve? 
Thank´s

**Comment by TBertuzzi** [comment]
Update to version 1.1.0
