### ISSUE TITLE
Reset zoom level

### ISSUE THREAD

**Issue by truXton222** [TBertuzzi/Xamarin.Forms.PinchZoomImage#9]
Hi, there is any way to reset the zoom of the PinchZoom component to the original value?

Thank you

**Comment by Thijsvdd1** [comment]
Hi! I just experienced the same situation where I wanted to reset with the double tap 

You can find my code I used for this here: 

https://github.com/TBertuzzi/Xamarin.Forms.PinchZoomImage/pull/11/commits/4107c4f7902ce0985a9a82a77b28152673ea2a4e

Hope you'r ehelped with this answer! :)

**Comment by TBertuzzi** [comment]
Double tap to return after your first double tap
